name: Execute Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:5.7.31
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306/3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379/6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Chekcout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Cache composer dependencies
        id: composer-cache-restore
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        if: steps.composer-cache-restore.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
      - name: Prepare .env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Clear Config
        run: php artisan config:clear
      - name: Database Migration
        run: php artisan migrate
        env:
          DB_PORT: 3306
          REDIS_PORT: 6379
      - name: Execute test
        run: ./vendor/bin/phpunit ./tests
        env:
          DB_PORT: 3306
          REDIS_PORT: 6379
